server {
    listen 8080;
    server_name localhost 127.0.0.1;

    client_max_body_size 0;
    proxy_request_buffering off;
    proxy_buffering off;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto http;
        proxy_pass http://artifactory:8082;
    }
}

server {
    listen 8443 ssl;
    server_name jcr.localhost jcr-proxy host.k3d.internal;

    ssl_certificate /etc/nginx/tls/tls.crt;
    ssl_certificate_key /etc/nginx/tls/tls.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size 0;
    proxy_request_buffering off;
    proxy_buffering off;
    proxy_read_timeout 900;
    proxy_send_timeout 900;

    location = /v2/token {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://artifactory:8082;
    }

    location ^~ /v2/docker-local/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://artifactory:8082;
    }

    location ^~ /v2/helm-local/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://artifactory:8082;
    }

    location /v2/ {
        rewrite ^/v2/(.*)$ /v2/docker-local/$1 break;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://artifactory:8082;
    }

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://artifactory:8082;
    }
}
