registry:
  pullSecret: harbor-credentials

images:
  busybox: harbor.airgap.local:5443/airgap/library/busybox:1.38.0
  postgis: harbor.airgap.local:5443/airgap/postgis/postgis:18-3.6
  pgadmin: harbor.airgap.local:5443/airgap/dpage/pgadmin4:9.16
  rabbitmq: harbor.airgap.local:5443/airgap/library/rabbitmq:4.3.2-management-alpine
  pgstac: harbor.airgap.local:5443/airgap/ghcr.io/stac-utils/pgstac:v0.9.11

secrets:
  postgresSuperUsername: postgres
  postgresSuperPassword: change-me
  geoserverUsername: geoserver
  geoserverPassword: change-me
  rabbitmqUsername: geoserver
  rabbitmqPassword: change-me
  rabbitmqErlangCookie: change-me
  pgadminPassword: change-me
  stacUsername: stac
  stacPassword: change-me

postgis:
  storage: 8Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "2"
      memory: 1536Mi

pgadmin:
  host: pgadmin.localhost
  tlsSecret: pgadmin-tls
  email: admin@example.com
  storage: 2Gi
  postgisHost: platform-platform-infra-postgis.platform-infra.svc.cluster.local
  postgisPort: 5432
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

rabbitmq:
  storage: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

pgstac:
  database: stac
  storage: 8Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "2"
      memory: 2Gi
