apiVersion: v1
kind: Secret
metadata:
  name: gscloud-runtime
type: Opaque
stringData:
  rabbitmq-username: {{ .Values.runtimeSecrets.rabbitmqUsername | quote }}
  rabbitmq-password: {{ .Values.runtimeSecrets.rabbitmqPassword | quote }}
  pgconfig-username: {{ .Values.runtimeSecrets.pgconfigUsername | quote }}
  pgconfig-password: {{ .Values.runtimeSecrets.pgconfigPassword | quote }}
  geoserver-admin-username: {{ .Values.runtimeSecrets.geoserverAdminUsername | quote }}
  geoserver-admin-password: {{ .Values.runtimeSecrets.geoserverAdminPassword | quote }}
  qgis-password: {{ .Values.runtimeSecrets.qgisPassword | quote }}
  stac-username: {{ .Values.runtimeSecrets.stacUsername | quote }}
  stac-password: {{ .Values.runtimeSecrets.stacPassword | quote }}
