apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platform-infra.fullname" . }}-postgis-init
  labels:
    {{- include "platform-infra.labels" . | nindent 4 }}
data:
  01-init-geoserver.sh: |
    #!/bin/sh
    set -eu
    psql -v ON_ERROR_STOP=1 \
      --username "$POSTGRES_USER" \
      --dbname "$POSTGRES_DB" \
      --set=gs_user="$GEOSERVER_DB_USERNAME" \
      --set=gs_password="$GEOSERVER_DB_PASSWORD" <<'EOSQL'
    SELECT format('CREATE ROLE %I LOGIN PASSWORD %L', :'gs_user', :'gs_password')
    WHERE NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = :'gs_user') \gexec
    SELECT format('CREATE DATABASE gscloud_config OWNER %I', :'gs_user')
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'gscloud_config') \gexec
    SELECT format('CREATE DATABASE gisdata OWNER %I', :'gs_user')
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'gisdata') \gexec
    EOSQL

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname gscloud_config \
      --set=gs_user="$GEOSERVER_DB_USERNAME" <<'EOSQL'
    CREATE EXTENSION IF NOT EXISTS postgis;
    CREATE SCHEMA IF NOT EXISTS pgconfig AUTHORIZATION :"gs_user";
    ALTER DATABASE gscloud_config OWNER TO :"gs_user";
    EOSQL

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname gisdata \
      --set=gs_user="$GEOSERVER_DB_USERNAME" <<'EOSQL'
    CREATE EXTENSION IF NOT EXISTS postgis;
    ALTER DATABASE gisdata OWNER TO :"gs_user";
    EOSQL
