apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-infra.fullname" . }}-secrets
  labels:
    {{- include "platform-infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-super-username: {{ .Values.secrets.postgresSuperUsername | quote }}
  postgres-super-password: {{ .Values.secrets.postgresSuperPassword | quote }}
  geoserver-username: {{ .Values.secrets.geoserverUsername | quote }}
  geoserver-password: {{ .Values.secrets.geoserverPassword | quote }}
  rabbitmq-username: {{ .Values.secrets.rabbitmqUsername | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmqPassword | quote }}
  rabbitmq-erlang-cookie: {{ .Values.secrets.rabbitmqErlangCookie | quote }}
  pgadmin-password: {{ .Values.secrets.pgadminPassword | quote }}
  pgadmin-pgpass: {{ printf "%s:%v:*:%s:%s" .Values.pgadmin.postgisHost .Values.pgadmin.postgisPort .Values.secrets.postgresSuperUsername .Values.secrets.postgresSuperPassword | quote }}
