module.exports = {
  catalogUrl: '/api/stac/',
  catalogTitle: 'GeoServer Cloud STAC',
  catalogImage: null,
  allowExternalAccess: true,
  allowedDomains: [],
  detectLocaleFromBrowser: true,
  storeLocale: true,
  locale: 'en',
  fallbackLocale: 'en',
  supportedLocales: ['de', 'ar', 'es', 'en', 'fr', 'it', 'ro', 'ja', 'pt', 'id', 'pl'],
  apiCatalogPriority: null,
  useTileLayerAsFallback: false,
  displayGeoTiffByDefault: false,
  displayPreview: true,
  displayOverview: true,
  buildTileUrlTemplate: null,
  getMapSourceOptions: null,
  pathPrefix: '/stac/',
  historyMode: 'history',
  cardViewMode: 'cards',
  cardViewSort: 'asc',
  showKeywordsInItemCards: false,
  showKeywordsInCatalogCards: false,
  showThumbnailsAsAssets: false,
  searchResultsPerPage: null,
  itemsPerPage: null,
  collectionsPerPage: null,
  maxEntriesPerPage: 1000,
  defaultThumbnailSize: null,
  crossOriginMedia: null,
  requestHeaders: {},
  requestQueryParameters: {},
  socialSharing: [],
  preprocessSTAC: null,
  authConfig: null,
  crs: {},
  footerLinks: null,
};
